# This is a sample build configuration for Java (Gradle).
# Check our guides at https://confluence.atlassian.com/x/zd-5Mw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: openjdk:8

pipelines:
  default:
    - step:
        deployment: production
        caches:
          - gradle
        script: # Modify the commands below to build your repository.
          # You must commit the Gradle wrapper to your repository
          # https://docs.gradle.org/current/userguide/gradle_wrapper.html
          - bash ./gradlew build
          
          - pipe: atlassian/sftp-deploy:0.3.1
            variables:
                  USER: 'root'
                  SERVER: '139.59.36.78'
                  REMOTE_PATH: '/home/formonk/build/'
                  LOCAL_PATH: 'build'
                  SSH_KEY: 'ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAQEAm1f8ne5QK6OUPyFlMnok2njfErzEja5dKsVeLV9o5yY+7QzL2EOE6e48KkY/7uFLHFnN1UZKF0wqrv5+VgAl0XAVDYHURYklhEif7fFUIiUKCiOJ/c7igpr+M1jc3ZskEaMLGJEzXw7wdbBPJUogO7JxEPeSVSc/hYrrz5TpfK27uhKu9eP+suoYWTf4imDSy20DBRPvk96MGoH3By2LoWhnJii1SWaEnRH3s01dPXZ8fY5lWwRPzjQtyuuwYSKiDgirF1BAWALeQVOQJEDLijzXNrNspFyetiIjPxL4fCrabg4QuEK1yVVJSuTP1joikvg3zj3iGANf4at3ERDOdQ== rsa-key-20190309'
